// Generated by scripts/write-app-config.mjs
// Owner can set DAPOERMUDA_API_BASE_URL before building web or Android assets.
window.DAPOERMUDA_APP_CONFIG = Object.assign({
  apiBaseUrl: "",
  requestTimeoutMs: 12000
}, window.DAPOERMUDA_APP_CONFIG || {});
